version: '3'
services:
  nginx:
    image: nginx:stable
    env_file:
      - .env
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - './conf:/etc/nginx/conf.d'
      - './certs:/etc/letsencrypt'
      - './certs-data:/data/letsencrypt'
    command: /bin/bash -c 'envsubst < /etc/nginx/conf.d/sites.conf.template > /etc/nginx/conf.d/sites.conf && nginx -g "daemon off;"'
  certbot:
    image: deliverous/certbot
    env_file:
      - .env
    depends_on:
      - nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    command: "certonly --webroot --webroot-path=/data/letsencrypt -d ${SERVER_NAME}"
